using System;
using System.Globalization;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Linq;

using static RecipeLoader.LogTools;
using static RecipeLoader.API;
using BepInEx;

// NOTE:
// This file is kind of ugly and could probably do with some improvement, but it's fine for now (until it wont be)
// 2026-08-13
// Review this if recipe schema changes in a new game update

namespace RecipeLoader;

internal static class FileParser
{

  // NOTE:
  // All assumptions about the document made in the methods below *must* be ensured by RLRecipeDirectiveFileValidator

  internal static RecipeSpecifier GetRecipeSpecifierFromRecipeXDocument(XDocument validDocument)
  {
    XElement root = validDocument.Root;

    StationType station = StringToStationMapper
      (root.Element("craftstation").Attribute("type").Value)!.Value!;

    InvBaseItem.CreativeCategory category = StringToCategoryMapper
      (root.Element("category").Attribute("type").Value)!.Value!;

    string targetName = root.Attribute("name").Value.Trim();

    return new RecipeSpecifier(targetName, new StationCategoryPair(station, category));
  }


  internal static InsertRecipeDirective
    CreateNewInsertRecipeDirectiveFrom(string filePath, XDocument validDocument)
  {
    GenericRecipeDirective genericDirective = CreateNewGenericRecipeDirectiveFrom(filePath, validDocument);
    XElement root = validDocument.Root;
    bool overwrite = root.Element("overwrite") != null;

    return new InsertRecipeDirective(genericDirective.Data, overwrite);
  }

  internal static ReplacementRecipeDirective
    CreateNewReplacementRecipeDirectiveFrom(string filePath, XDocument validDocument)
  {
    GenericRecipeDirective genericDirective = CreateNewGenericRecipeDirectiveFrom(filePath, validDocument);
    return new ReplacementRecipeDirective(genericDirective.Data);
  }


  // This is kind of ugly but it works for what it's supposed to do
  internal static GenericRecipeDirective CreateNewGenericRecipeDirectiveFrom(string filePath, XDocument validDocument)
  {

    // === Helpers ===

    bool GetBoolAttributeValue(XAttribute? attribute, bool defaultVal = false)
    {
      if (attribute == null)
      {
        return defaultVal;
      }

      string input = attribute.Value?.Trim().ToLower() ?? "<no input>";

      if (input == "true")
      {
        return true;
      }
      if (input == "false")
      {
        return false;
      }

      Warn($" {filePath} : '{attribute.Name} is not one of: 'true', 'false'. Got {input}. Defaulting to {defaultVal}");
      return defaultVal;
    }


    string GetStringAttributeValue(XAttribute? attribute, string defaultVal = "")
    {
      if (defaultVal == "")
        defaultVal = $"MISSING_VALUE:{filePath}";
      if (attribute == null)
      {
        Warn($" {filePath} : GetStringAttributeValue called with a null attribute reference.");
        return defaultVal;
      }

      string? input = attribute.Value?.Trim();
      if (input == null)
      {
        Warn($" {filePath} : {attribute.Name} has no value. Using autogenerated default: {defaultVal}");
        return defaultVal;
      }
      return input;
    }

    double? GetNullableDoubleAttribute(XElement element, string attributeName)
    {
      var value = element.Attribute(attributeName)?.Value;
      return value != null &&
             double.TryParse(
                 value,
                 NumberStyles.Float,
                 CultureInfo.InvariantCulture,
                 out var result)
          ? result
          : null;
    }

    int? GetNullableIntAttribute(XElement element, string attributeName)
    {
      var value = element.Attribute(attributeName)?.Value;
      return value != null &&
             int.TryParse(
                 value,
                 NumberStyles.Integer,
                 CultureInfo.InvariantCulture,
                 out var result)
          ? result
          : null;
    }

    float? GetNullableFloatAttribute(XElement element, string attributeName)
    {
      var value = element.Attribute(attributeName)?.Value;
      return value != null &&
             float.TryParse(
                 value,
                 NumberStyles.Float,
                 CultureInfo.InvariantCulture,
                 out var result)
          ? result
          : null;
    }


    // === Data getters ===

    // NOTE: Change this and ValidateRecipeDirective to support multiple quest/achieve locks if the game ends up 
    // supporting/using them as well
    RecipeXml.Locked? GetLocked(XElement root)
    {
      XElement? lockedElement = root.Element("locked");
      if (lockedElement == null)
      {
        return null;
      }

      List<RecipeXml.LockedInfo> lockedInfo = [];

      foreach (XElement lockedDirective in lockedElement.Elements())
      {
        if (lockedDirective.Name == "quest")
        {
          lockedInfo.Add(
              new RecipeXml.Quest
              {
                npc = GetStringAttributeValue(lockedDirective.Attribute("npc"))
              } // Already checked for validity in ValidateRecipeDirective
              );
          break;
        }

        if (lockedDirective.Name == "achieve")
        {
          lockedInfo.Add(
              new RecipeXml.Achieve { title = GetStringAttributeValue(lockedDirective.Attribute("title")) } // Already checked for validity in ValidateRecipeDirective
              );
          break;
        }

      }
      return new RecipeXml.Locked { info = [.. lockedInfo] };
    }

    Item GetItemFromElement(XElement element)
    {
      string? groupName = element.Attribute("group")?.Value?.Trim();
      if (groupName != null && RLItemGroups.GetGroup(groupName) == null)
      {
        // This shouldn't happen, im already validating this in ValidateRecipeDirectiveFile
        Warn($"Nonexistant group: {groupName}");
        groupName = null;
      }


      return
        new Item
        (
  element.Attribute("name")?.Value, // null OK
  GetNullableIntAttribute(element, "count") ?? 1,
  GetNullableIntAttribute(element, "exactCount"), // null OK

  groupName, // null OK
  GetNullableIntAttribute(element, "data") ?? 0,
  GetBoolAttributeValue(element.Attribute("inheritData")),

  GetBoolAttributeValue(element.Attribute("compareIngredientData"))
);
    }

    List<List<Item>> GetRows(XElement root, RecipeSpecifier specifier)
    {
      (int rowCount, int columnCount) = GetStationRowsColumns(specifier.Station); // Rows/Columns guaranteed 
      // to be equal or less than this by ValidateRecipeDirectiveFile
      List<List<Item>> result = [];

      int missingRows = rowCount;

      IEnumerable<XElement> rows = root.Elements("row");
      foreach (XElement row in rows)
      {
        int missingItems = columnCount;
        missingRows--;

        List<Item> addedItems = [];
        IEnumerable<XElement> items = row.Elements("item");

        foreach (XElement item in items)
        {
          addedItems.Add(GetItemFromElement(item));
          missingItems--;
        }
        // for (int i = 0; i < missingItems; i++)
        // {
        //   addedItems.Add(GetItemFromElement(new XElement("item")));
        // }

        result.Add(addedItems);

      }

      // for (int i = 0; i < missingRows; i++)
      // {
      //   List<Item> emptyRow = [];
      //   for (int j = 0; j < columnCount; j++)
      //   {
      //     emptyRow.Add(new Item());
      //   }
      //   result.Add(emptyRow);
      // }

      return result;

    }

    Timed? GetTimed(XElement root)
    {
      XElement? timed = root.Element("timed");

      if (timed == null)
      {
        return null;
      }

      return new Timed
      {
        Minutes = GetNullableDoubleAttribute(timed, "minutes") ?? 1,
        Cost = GetNullableFloatAttribute(timed, "cost") ?? 0,

        Seconds = GetNullableDoubleAttribute(timed, "seconds")
      };


    }

    // --
    // Actual directive build begins here


    XElement root = validDocument.Root;
    RecipeSpecifier specifier = GetRecipeSpecifierFromRecipeXDocument(validDocument);


    bool hidden = GetBoolAttributeValue(root.Attribute("hidden"));
    bool hiddenUntilUnlocked = GetBoolAttributeValue(root.Attribute("hiddenUntilUnlocked"));
    bool lockedInCreative = GetBoolAttributeValue(root.Attribute("lockedInCreative"));
    bool compareIngredientData = GetBoolAttributeValue(root.Attribute("compareIngredientData"));
    RecipeXml.Locked? locked = GetLocked(root);

    bool allowMixed = root.Element("allowMixed") != null;

    List<List<Item>> rows = GetRows(root, specifier);
    Item result = GetItemFromElement(root.Element("result"));
    Timed? timed = GetTimed(root);



    return new GenericRecipeDirective(new GenericRecipeDirectiveData(
          specifier,
        hidden,
        hiddenUntilUnlocked,
        lockedInCreative,
        compareIngredientData,
        locked,

        allowMixed,

        rows,
        result,
        timed
        ));

  }


}


